### ISSUE TITLE
Missing maps - maps included with game engine not in github

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-maps/Project#12]
big_world, new_world_order, are missing from github as map projects. Looks like  maps included with game engine have not been uploaded as github projects yet

**Comment by DanVanAtta** [comment]
@ron-murhammer , let me know if you want to give this a shot for a map or two, practice with the createRepo.sh script. Otherwise I'll take care of it in the coming weeks.

**Comment by ron-murhammer** [comment]
@DanVanAtta So this would be moving the maps that exist in the main code base and putting them in separate map repos?

**Comment by DanVanAtta** [comment]
Yup. Each one needs to be zipped, and then run `createRepo.sh`.

I added some getting started notes to the script `usage` documentation: https://github.com/triplea-maps/Project/blob/master/bin/createMapRepo.sh

A key thing is setting up  the password/token files. More details in the `usage` function referenced above.

**Comment by ron-murhammer** [comment]
@DanVanAtta Ok. Though if we do that then is there a clean way to bundle those maps with the installers?

**Comment by DanVanAtta** [comment]
Yes, though exactly how to bundle it has not yet been discussed/determined.

Tentatively, I was planning to have a set of `wget` statements that download the map zips. For perhaps some added context, today travis is downloading install4j and installing it whenever it does a build. So I'm not worried about the download, only thing I'm worried about is keeping the list updated.

Given it's one file, only a dozen maps, and github allows in place editing from web browser, we at the very least have time to come up with a better solution. With that stated, I am open to considering any good ideas.

**Comment by DanVanAtta** [comment]
The maps that were included with the game engine are now uploaded.
