### ISSUE TITLE
New map: Big World 1939

### ISSUE THREAD

**Issue by KaiMAD** [triplea-maps/Project#19]
#I propose a map exactly like Big World 1942, except set in 1939; I have created just such a map, and it is included [here.](https://github.com/KaiMAD/big_world_1939)

**Comment by DanVanAtta** [comment]
Repo created: https://github.com/triplea-maps/big_world_1939

You'll need to submit a PR into this file to have the map actually be available for in-game download: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml
