### ISSUE TITLE
Would like Invasion USA pull to Github

### ISSUE THREAD

**Issue by WCSumpton** [triplea-maps/Project#20]
Working on a mod to this map.

**Comment by DanVanAtta** [comment]
I should get a chance to upload to Github later tonight. Would you please post a link to the 'Invasion USA' zip file?

**Comment by WCSumpton** [comment]
Hope this helps, its under 'maps hosted elsewhere' link on the sourceforge site. https://sourceforge.net/projects/tripleamaps/files/maps/backup%20of%20maps%20hosted%20elsewhere/Invasion_USA.zip/download

**Comment by DanVanAtta** [comment]
Done: https://github.com/triplea-maps/invasion_usa/

You've been added to an team  'WCSumpton' which has write permission for the repo. Whenever you deploy changes (to master), a new map zip will be created automatically for you here: https://github.com/triplea-maps/invasion_usa/releases

Please submit a PR with an update to this file: https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml, for the map to be included in the game engine.

**Comment by DanVanAtta** [comment]
Added to the project readme some setup instructions: https://github.com/triplea-maps/Project/blob/master/README.md  , please check for the updates @WCSumpton
