### ISSUE TITLE
Ownership of Greyhawk Wars

### ISSUE THREAD

**Issue by panguitch** [triplea-maps/Project#23]
I'm claiming ownership of Greyhawk Wars and Greyhawk.

**Comment by DanVanAtta** [comment]
@panguitch  Are you original author, or just wishing to update the maps?

**Comment by panguitch** [comment]
Yes, I'm the original author. It's my email address etc. in the game notes.

**Comment by DanVanAtta** [comment]
Panguitch, you should see an invite to the team 'panguitch'. That team now has admin access to the greyhawk war maps (meaning you can write to the repo, and you can add additional people to that team if you choose).
