### ISSUE TITLE
Napoleanic (instead of Napoleonic) Empire Map skin

### ISSUE THREAD

**Issue by panther2** [triplea-maps/Project#55]
... just a cosmetic typo-issue in triplea_maps.yaml 
(lines 890/895)

**Comment by panther2** [comment]
I am ready to correct this after 
https://github.com/triplea-maps/napoleonic_empire-political_map_skin/pull/1
has been merged, so the new version can be included, too.

**Comment by DanVanAtta** [comment]
Running an update all maps script in a few moments to ensure we have the latest maps at the moment listed.

**Comment by panther2** [comment]
OK, I will hold on with changing the version info from 0.5 to 0.8 and the typos until the script has run and #56 has been merged.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-maps/Project/pull/56/files is waiting for:  https://github.com/triplea-game/triplea/pull/1140

The version update from 0.5 to 0.8 is done.

**Comment by panther2** [comment]
After #58 has been merged I will close this issue,

**Comment by panther2** [comment]
Merged and closed. Thanks.
