### ISSUE TITLE
I'm a Gitnoramus

### ISSUE THREAD

**Issue by panguitch** [triplea-maps/Project#64]
I'm trying to release Greyhawk Wars 1.9. It plays just fine if you place the zip directly into your downloadedMaps
[Greyhawk_Wars.zip](https://github.com/triplea-maps/greyhawk_wars/files/572720/Greyhawk_Wars.zip)

However, I'm trying to update it here in the repository and can't get it to play (https://github.com/triplea-maps/greyhawk_wars/commits/master). The images in the docs folder don't show in the game notes, and when I try to launch the map it fails with no message.

I'm using Git Desktop. Trying to. But it's going wrong somehow. Anyone care to hold my hand and walk me through whatever I'm doing wrong?

**Comment by simon33-2** [comment]
https://www.youtube.com/watch?v=Y9XZQO1n_7c&list=PLIe7tH9wjKEd6fRxDYMRxS693bSLb17_4

**Comment by simon33-2** [comment]
Basically, you need to fork the repository in github, then on your PC clone the fork, make your changes, commit, push and then open a pull request (back on github).

To keep up to date you also need to set up a remote for the parent repository. You can also clone this one and update the remotes to allow pushing to your fork. Given that it sounds like you know the changes you want to make already, it might be easier to clone the fork rather than the usual way of doing it which is to clone the parent.

**Comment by DanVanAtta** [comment]
There are two places with map making documenation:
- http://www.triplea-game.org/how_to_create_custom_maps/
- https://github.com/triplea-game/triplea/tree/master/docs/map_making

There is a slow migration of everything to the triplea-game.org website, right now documentation is a bit scattered

**Comment by DanVanAtta** [comment]
One way to get up and going, go to your 'triplea/downloadMaps' folder, and then from there run:
`git clone git@github.com:triplea-maps/greyhawk_wars.git`

Load the game, and verify the map is picked up.

Then you have a working map, and it is connected to git. Github has  a client tool, it can be used to help stage and commit files.

**Comment by panguitch** [comment]
This is a large update, so I had to do it in a batch. I used GitHub Desktop and it seemed to work. But the map won't run. On the other hand, if I clone the map and then paste that clone into my downloadedMaps folder it runs just fine.

In other words, I can clone the map and paste its folder into downloadedMaps and it works. But if I use Download Maps inside TripleA to download the map, it doesn't work. Images in the docs folder don't display and when you try to start the game it fails.

Why would it work to paste the cloned files but not to download it through TripleA?

**Comment by simon33-2** [comment]
Most obvious answer is what is being downloaded is different to what you are testing. Have you verified that this is not the case?

**Comment by simon33-2** [comment]
I've tried to have a look at your issues but I can't get the map to run either.

I don't think this is a git problem. I tried your download in the OP and that wouldn't run either. Somehow there's a space being inserted in one of the paths which is wrong.

**Comment by simon33-2** [comment]
There's a stuff load of dos end of lines. i.e. control-M before the control-J at the end of the line. I think UNIX end of line is needed - control-J only.

Still having problems with it though.

**Comment by panguitch** [comment]
Odd. Double-checked and the zip file in the OP runs for me if I place it in downloadedMaps folder.

I'm afraid what you're saying about end of lines is entirely over my head. Creating this map for TripleA is the closest I've come to anything like coding. I was quite proud that it worked and that people were enjoying it. Pride goeth before the fall and whatnot.

Here's what I did to begin with: After I branched Greyhawk Wars 1.0 to GitHub Desktop I took the files I had been working on for the past year (GW 1.1) and pasted them over the cloned files. GitHub Desktop recognized thousands of changes across dozens of files. I pushed (or is it pulled?) those changes back to the repository. But while GW 1.1 in my laptop's Git folder can be copied to downloadedMaps and played, the one in the repository can't and no error log pops up.

**Comment by simon33-2** [comment]
lmgtfy

http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html

I think you need to familiarise yourself with the concept of Windows vs Unix end of line. It is probably a significant part of your problem.

**Comment by panguitch** [comment]
OK. I used Notepad++ to convert the xml, text, and property files to unix line endings. Then I published it back to the repository (shows as [release 0.25](https://github.com/triplea-maps/greyhawk_wars/releases)). Sadly, the same problems persist.

It must have something to do with the way the map is packaged when downloaded within the game interface. Here's why I say that: if you download GW within TripleA it doesn't work, even with the new unix line endings. 

However, you can go to the files which have just been installed by the game in downloadedMaps in the zipped greyhawk_wars-master folder. Extract all the files. There are two greyhawk_wars-master folders, one nested in the other. Edit the name of the inner one to be greyhawk_wars. Now copy it and paste in the downloadedMaps folder. Delete the zipped folder the game downloaded, leaving just the extracted version. The game will play this extracted version just fine, with none of the problems.

I'm not good at explaining this. Here's a quick [screen capture](http://screencast.com/t/xghAW9v1Di) of what I'm saying, showing that the map doesn't work as downloaded by the game, but if extracted it works fine.

**Comment by simon33-2** [comment]
@panguitch ,
Looks like the problem was the upper case in the mapName. I've opened a pull request for this fix here: https://github.com/triplea-maps/greyhawk_wars/pull/3

Assuming you have been granted write access to this repo, you should be able to just click "merge" and you will grab the fix.

**Comment by panguitch** [comment]
Good grief. I knew it had to be something silly like that. Many thanks for helping me figure this out. I'm very happy to have it working and downloadable in-game, available to players.
