### ISSUE TITLE
List of options

### ISSUE THREAD

**Issue by JJKAL** [triplea-maps/Project#66]
Does there exist an exhaustive list of all options for editing? E.g., all available options in terms of politicalactionattachment, for instance, "actionAccept" etc.? If yes, where can I find it? Thanks!

**Comment by panther2** [comment]
I am desperatly searching for something like this, too

I have been pointed to the xml of Pact of Steel 2 in the past.
You will find a lot of information there, although it does not reflect the latest version ...
and it is not easy to see all the dependencies.
... but that is better than nothing....

**Comment by JJKAL** [comment]
Dear panther, thanks. I'll have a look at pos2. The only thing I found so far is:
http://axisandallies.wikia.com/wiki/Category:Properties
You can choose a subcategory and then you get a list. The list seems not to be exhaustive though and the explanations are vague. But nonetheless it might help you...

**Comment by panther2** [comment]
@JJKAL 
Interesting, thanks... I did not know about that page.
