### ISSUE TITLE
Maps with open PRs for SBR

### ISSUE THREAD

**Issue by simon33-2** [triplea-maps/Project#67]
Can someone merge these PRs:

https://github.com/triplea-maps/world_war_ii_v3/issues/2
https://github.com/triplea-maps/world_war_ii_v6_1941/issues/1
https://github.com/triplea-maps/world_war_ii_pacific/issues/2
https://github.com/triplea-maps/world_war_ii_europe/issues/2

**Comment by DanVanAtta** [comment]
done
