### ISSUE TITLE
Git Download of All Maps

### ISSUE THREAD

**Issue by williamdekryger** [triplea-maps/Project#7]
Great job on these map migrations, especially @DanVanAtta! I have a quick question: Will there be a way to automatically install all maps and keep them updated via Git? If there was one repo, maybe with [Git submodules] (https://git-scm.com/book/en/v2/Git-Tools-Submodules) we could make this work. Or is there a plan for a better system?

**Comment by DanVanAtta** [comment]
git submodules won't help very much, it also makes the work flow really complicated.

Here is a one liner to clone all of the repo's:
for i in $(curl -s https://api.github.com/orgs/triplea-maps/repos 2>&1 | grep ssh_url | sed 's|.*: "||g' | sed 's|",$||'); do git clone $i; done

(intent will be to have such scripts checked in under Project/bin)

**Comment by williamdekryger** [comment]
I actually brought this up in case you wanted to add that to the docs (or I could put it on the website). Thoughts? Is this a viable long-term solution, or should we tell users to download their maps via the built-in installer. In the future, it would be cool if TripleA had some command-line tools that included map installation. That alone may be simple enough, though I realize there are other priorities...

**Comment by DanVanAtta** [comment]
It's a good command for developers / map makers, but not for the every day user who wants to 'download all maps'.

An in-game feature I think is the best way to go there, a 'donwload all' button.

**Comment by ZjelcoP** [comment]
Though a simple CTRL-A also does the trick of downloading all maps. Perhaps make that known to people.

One thing I did notice is that the more maps you have, the longer it seems to take to switch maps.
This made me stop downloading all. Perhaps it could be helped in an other way. Don't know why the engine has to check every map every time.

**Comment by DanVanAtta** [comment]
Some good news about having many maps - I submitted recently a pull request to fix how the game engine parses maps.  The reason it needed to do it was to know which maps are installed, but it did it by reading through all the content :-1:  (largely a limitation of the time it was written, Java7+ has fixes we can use now that speeds things up)

With 110 maps (1.8G) downloaded, the load time was cut from 20s to 2s    : https://github.com/triplea-game/triplea/pull/240
