### ISSUE TITLE
Trouble releasing map

### ISSUE THREAD

**Issue by alkexr** [triplea-maps/Project#70]
I have updated my map to a new version and released it. The problem is, I have been working on this:
https://github.com/alkexr/large_middle_earth
which is more or less irrelevant, if I get it right, and what I should work on is
https://github.com/triplea-maps/large_middle_earth

So, how do I magically translocate (pull? confused about terminology) the version in the wrong one and merge it into the correct one?

Also, how do I update the image in the description? In triplea_maps.yaml all image links point to the same website, do I have to upload the image there? (And how do I do that?)

Note: both
https://github.com/triplea-maps/Project/wiki/Map-Makers%3A-Request%20that%20a%20new%20map%20version%20go%20live
and
https://github.com/triplea-maps/Project/wiki/Update-Triplea_maps.yaml
have a broken link to
https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

**Comment by simon33-2** [comment]
You need to open a pull request.

This is different from a straight pull - you are asking someone else to pull something to them whereas a normal pull is you pulling something to your machine.

If approved, that should be half the work but you also need to move the version number on in triplea_maps.yaml - this signals user's computers that their downloaded copy is out of date and needs to be updated.

There is another option for changing the images - change the triplea_maps.yaml, which as I've described above you need to change anyway. Obviously this means they need to be hosted somewhere quite static.

**Comment by simon33-2** [comment]
I can't see a fork for your user id. You'll also need to create that. Honestly, I think the best option will be to create your fork (click button on website), clone your fork to a new location on your local machine, reapply your changes, test it again in case something has gone wrong in the process, commit, push, create PR on website.

You'll need to do the same cycle again again to update the triplea_maps.yaml, which gets even more tricky when you need to keep it up to date with others changes! (you need to add a remote for the public repo)

Is that clear?

**Comment by alkexr** [comment]
Thanks for the answer. It's kind of clear.

The problem was, it wasn't a pull request between forks (which I could have done), but a pull request between two seemingly unrelated repos. But I already just simply reuploaded all of it. (It did take a while.)

The triplea_maps.yaml update is already in progress, but I guess no one actually knows where I am supposed to upload the image. https://github.com/triplea-game/triplea/pull/1453

So, since everything is already in progress, this issue can be closed.
