### ISSUE TITLE
Create new Domination_1914-Weltpolitik repo

### ISSUE THREAD

**Issue by surtur2** [triplea-maps/Project#71]
Hi, admins.  I'd like to upload something I've been working on to github, so it is easier to distribute and solicit feedback.

Can a new Domination_1914-Weltpolitik repo be created under triplea-maps/?

Thanks!

**Comment by beelee1** [comment]
Hi surtur2
This link will give the steps to go through:

[https://github.com/triplea-maps/Project/tree/master/MapMakingTools](url)

Also there's some more info in #69

**Comment by surtur2** [comment]
Thanks for that; but the thread you are referring to is a fork of an existing repo.  I'd like a new repo for a new map (as I've made changes to the baseline, etc.), which I believe requires the admins to create it under the triplea-maps organization, if I'm not mistaken?

**Comment by beelee1** [comment]
@surtur2 
I think in that case you make your own repo and then when it's ready you hit change ownership. Then the admins take it from there.

I'm not 100% sure as this is pretty new to me

**Comment by DanVanAtta** [comment]
@surtur2 , also be aware when you are working on your map, if you create a repo, you can clone it directly into the `<user_home>/Triplea/downloadmaps/` folder, and the game should pick it up. You should find that you do not need to do any zipping/unzipping

**Comment by DanVanAtta** [comment]
eg: `<user_home>/Triplea/downloadmaps/domination_1914-weltpolitik`

(note repo naming standard is all lower case, actual map name is set in the various configuration files)

**Comment by surtur2** [comment]
Ok.  Got everything uploaded to the repo.  To whom do I transfer ownership to?

**Comment by beelee1** [comment]
I'm not certain as I've never actually done it, but @simon33-2  told me "triplea-maps". Idk if that is exactly how it needs to be worded but you could try it.

The @ sign notifies people, so maybe he'll chime in if that's not correct

**Comment by simon33-2** [comment]
That's correct.

**Comment by surtur2** [comment]
"You don’t have the permission to create repositories on triplea-maps"

@simon33-2 I'm assuming either I have to join something or admins need to permission me for something?

**Comment by simon33-2** [comment]
I would presume you need to be permissioned or have it done for you. I can't do it.

**Comment by DanVanAtta** [comment]
@surtur2 the error message you post does not quite make sense - the transfer option should be on the bottom of this page: https://github.com/surtur2/domination_1914-weltpolitik/settings

**Comment by surtur2** [comment]
@DanVanAtta - that's how I got the message.  To reproduce for me:

![before](https://cloud.githubusercontent.com/assets/25858085/23148698/45a73de0-f7b5-11e6-813f-2474a0ff6af9.png)

I press the red button, and then I get this:

![after](https://cloud.githubusercontent.com/assets/25858085/23148699/45a8ad10-f7b5-11e6-9719-f3609d6a3617.png)

Am I supposed to fill in the repo name and/or organization name with something else?

**Comment by DanVanAtta** [comment]
Interesting @surtur2 , the next screen for me asks which teams should have access to the map. 
Instead, I was able to fork your repo into the 'triplea-maps' organization,  https://github.com/triplea-maps/domination_1914-weltpolitik

**Comment by surtur2** [comment]
So I guess from here on out new changes should be forked from the triplea-maps fork?

And to add it to the download index I should fork, edit, and pull triplea-maps/Project/blob/master/production_config/triplea_maps.yaml?

**Comment by panther2** [comment]
Version control for the ingame download is managed here:

https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml

**Comment by surtur2** [comment]
I've forked triplea and am trying to edit the .yaml file.  I can download the domination_1914-weltpolitik .zip + .properties file, but when I try to play the game, it complains about how it can't find the map (polygons.txt).  I'm assuming this is some kind of issue with naming conventions.

What is used for what?  And more importantly, what needs to match what?

In the .xml, there are:
property mapName = "Domination_1914-Weltpolitik"
info name="Domination 1914-Weltpolitik"

There is also the README.md, which has:
# Domination_1914-weltpolitik
Domination 1914: Weltpolitik

And of course, the name of the downloaded .zip:
domination_1914-weltpolitik-master.zip

**Comment by panther2** [comment]
The property mapName hast to be:

`<property name="mapName" value="domination_1914-weltpolitik" editable="false"/>`

So it has to match the map folder name.

It will run fine then.

**Comment by surtur2** [comment]
Just confirming that I should make changes to the triplea-maps fork of the map, and not my personal master

**Comment by DanVanAtta** [comment]
You can take your pick given you have write access to the triplea-maps fork.
You can push a branch to your personal master, and submit a PR from there. Since you can also create new branches in the triplea-maps fork, you can create/push a branch there and submit a PR. It's a question of where you want your branches to live and personal preference, both would work.

**Comment by simon33-2** [comment]
The least process way is to push directly to triplea-maps/<map>/master. That way you don't need to create pull requests etc.

That is what the users will see so any other path to get there is necessarily indirect.

**Comment by surtur2** [comment]
Ok, I've pushed changes to the mapName, and I've created a pull request for the .yaml edit:
https://github.com/triplea-game/triplea/pull/1556
