### ISSUE TITLE
Map Making Question

### ISSUE THREAD

**Issue by beelee1** [triplea-maps/Project#72]
Not sure if there is a place on Github for these type questions or not. If so would someone please direct me to the correct one ? I posted at new and old triplea forums as well. Anyway...placement/removeUnits

Is there a way to have the new units active the turn they show up ? They show up on combat move, which I believe is hard coded, but they won't move until next turn. I've tried several things and did a lot of searching but no luck.

Also can -reset- reset more than one thing at a time. E.g. airfield gives movement to 3 units. I can reset where one gets adjusted movement, but the other two get no extra movement at all. Tried multiple triggers and adding them all into one and any other combination I could think of. No go.

I assume the -reset- resets count="-reset-X:X" only ? That would now become the only,in this case, givesMovement attached ?

**Comment by beelee1** [comment]
@FrostionAAA 
sorry to bother you but I don't know where to ask these questions. Do you know how to make a trigger that changes unitAttachments ? I saw it discussed here:

[http://tripleadev.1671093.n2.nabble.com/Two-Questions-Disabling-player-step-preventing-unit-from-entering-combat-tp7589939.html](url)

but I can't figure it out. What I'm trying to do is change the movement an airfield gives. When a tech is activated it then allows a condition to be true which another trigger can use to -reset- the givesMovement for the airfield. 

Been trying for a couple days and would appreciate any help.

**Comment by FrostionAAA** [comment]
I have not played around with triggers that gives ingame Airfield movement bonuses. I have only one map that has unit stat changing features and that is the Star Trek map. It has a tech system that allows for unit stat upgrades with chance/dice dependent tech triggers. Maybe you should look at that XML. It is downloadable ingame.

I looked a good deal at the PoS2.xml when making these tech based unit stat changes. But I also remember that it is actually a quite restricted system that did not allow for every form of stat change I could think of.

**Comment by FrostionAAA** [comment]
I might not understand what exactly you want a unit to do and what you are asking for. Maybe you should post your question in the above thread if it is concerning the something in relation to what we discussed. It is a longer thread and right now would have to read up on it to understand what was being discussed.

**Comment by beelee1** [comment]
Thanks for the reply Frostion. I'll post in the other thread
