### ISSUE TITLE
Issue with Map Maker

### ISSUE THREAD

**Issue by AArtheon** [triplea-maps/Project#74]
So, is the version 2 of the Maker limited for certain operating systems? Maybe this has been answered, but I couldn't find it...

**Comment by panther2** [comment]
Are you referring to the built in MapCreator or Beta MapCreator?
Have you considered the new folder structure for 1.9 maps?

What exactly is your issue?

**Comment by AArtheon** [comment]
Essentialy, my issue is that when I try to start the .jar, a dialogue box
appears saying that it cannot start (I think something about finding the
.jar file, but I'll have to check when I get home)

**Comment by AArtheon** [comment]
The Beta Creator, I cannot locate the built-in one. Which subfolder is it
in?

**Comment by panther2** [comment]
What TripleA-version are you using?
![1](https://cloud.githubusercontent.com/assets/20812775/24251262/d30a657c-0fd9-11e7-91d9-c3698c46a522.gif)

**Comment by AArtheon** [comment]
Latest version
Okay, I'll try it that way
Thanks a lot

**Comment by AArtheon** [comment]
I finished, thank you for your help. I initially used the GitHub file in
Map Making v2, the .exe one, so that was the problem

**Comment by panther2** [comment]
@AArtheon 

Sounds good... you are welcome. :smiley: 
Please close this issue, in case you have no additional questions concerning this topic.

**Comment by AArtheon** [comment]
Will do, right away
Thanks again 😀
