### ISSUE TITLE
Iron War

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-maps/Project#75]
This BETA (v0.1) map is now transferred to triplea-maps, and I think the folders are as they should be:
https://github.com/triplea-maps/iron_war

@ron-murhammer or @DanVanAtta would you add the appropriate non map GitHub files in the root now?

I think I can manage to edit the yaml file myself. I think as Iron War is still BETA it should be in the experimental category, right?

PS: I will make am Iron War map thread at the new forum soon.

**Comment by DanVanAtta** [comment]
There is no need for non map github files anymore : )
The maps are pulled from the latest version, which lets us use the automatic zip packaging provided by github. Only the yml should now be updated it sounds.

**Comment by FrostionAAA** [comment]
Ahh OK. Then my next step is to update the yaml file. I will close this issue. Thanks DanVanAtta.
