### ISSUE TITLE
Can I have a new repo with write access and the ability to grant write access?

### ISSUE THREAD

**Issue by simon33-2** [triplea-maps/Project#76]
We want to do some experimental changes for Global 1940. The ideal would be to have our own downloadable repo and dub it experimental.

Can this be done? I reckon call it "Global_1940_Redesign_Testing"

**Comment by panther2** [comment]
Not sure @simon33-2 ... but as far as I remember this is done as follows:

- create a repo on your own, for example simon33-2/G40_redesign
- do whatever you want to do there
- when "ready" change ownership of that repo to triplea-maps so it becomes triplea-maps/G40_redesign

I saw it happening like this in the past...

**Comment by simon33-2** [comment]
When I try to transfer the ownership, I get the error that I don't have permission to transfer repositories on triplea-maps.

**Comment by panther2** [comment]
I think @DanVanAtta or @ron-murhammer need to do something here then,
I recalled starting from here: https://github.com/triplea-maps/Project/issues/71#issuecomment-281218444

**Comment by simon33-2** [comment]
Here's the repo I'm trying to transfer: https://github.com/simon33-2/Global_1940_Redesign_HouseRules

**Comment by DanVanAtta** [comment]
Forked it here: https://github.com/triplea-maps/Global_1940_Redesign_HouseRules
Team simon33-2 has been created and added with admin, you should see a request to join  @simon33-2

**Comment by simon33-2** [comment]
Thanks @DanVanAtta
