### ISSUE TITLE
Cernelius requests to be added to its own map team

### ISSUE THREAD

**Issue by Cernelius** [triplea-maps/Project#79]
I want to add this (playable) map to the download list:
https://github.com/Cernelius/270bc_variants
Please, send me an invitation to join my own map team at triplea-maps.

**Comment by DanVanAtta** [comment]
I need to update the docs, for the record the steps for admin are:
- fork repo to triplea-maps
- add author as a collaborator in settings > teams (admin so they can form their own teams)

I need to update the docs. We don't really need this 1:1 team thing anymore I don't think.

Anyways, that is done @Cernelius , you should have an email for access: https://github.com/triplea-maps/270bc_variants

**Comment by Cernelius** [comment]
Right. So not anymore transfer ownership, but request to admins to fork (duplicate) the repo, right? Then the user can decide to delete the original, if he wants to, correct?

Thanks.

Some more questions, for updating the yaml. Where am I supposed to upload the 400 wide pixel of the image (probably not in sourceforge, where the current TripleA_270BC_mini.png is) and, considering the increased wideness of the download window, is it still mandatory for the image to be exactly 400 pixels wide or is there a different standard now? Only PNG or also JPEG?
Am I supposed to upload it inside the same map like:
https://github.com/triplea-maps/iron_war/blob/master/map/EXTRA/MiniSnapshot.png
and exactly in a subfolder called "EXTRA"? Looks a bit strange. I would rather upload it beside the README, outside of the map folder.

**Comment by Cernelius** [comment]
Main question is, does "fork" mean that this thing in here is stand-alone and I can go totally delete:
https://github.com/Cernelius/270bc_variants
(to avoid having a duplicate around)

**Comment by ssoloff** [comment]
@Cernelius 

> Where am I supposed to upload the 400 wide pixel of the image

When I was creating a new repo for the Map Making Tutorial map, I looked for other maps that host their thumbnail on GitHub instead of SourceForge.  The convention I found was that they created a new `description` folder parallel to `map` and placed the thumbnail within that folder.  For example, see the [Star Wars: Galactic War](https://github.com/triplea-maps/star_wars_galactic_war) map.

**Comment by Cernelius** [comment]
Well, doubt that is a convention, since the same mapmaker did it differently in his latest creation:
https://github.com/triplea-maps/iron_war/blob/master/map/EXTRA/MiniSnapshot.png
I like it better the Star Wars way. I don't think it should stay inside the map folder, as I said.
I guess maybe also having some standards for the name of the image, like should I call it "TripleA_270bc_variants_mini"?

**Comment by ssoloff** [comment]
Yes, probably not an official convention. :smiley:  But of the ten thumbnails hosted on GitHub, seven are under `description`, one under `map/EXTRA`, and two were uploaded as standalone files to the GitHub cloud:

```
$ grep -P 'img:\s*https://' triplea_maps.yaml 
  img: https://cloud.githubusercontent.com/assets/12397753/18229195/05ef3d68-7224-11e6-9698-f21923d51858.png
  img: https://raw.githubusercontent.com/triplea-maps/age_of_tribes/master/description/AoT_mini.png
  img: https://raw.githubusercontent.com/triplea-maps/caribbean_trade_war/master/description/CaribbeanTradeWar_mini.png
  img: https://raw.githubusercontent.com/triplea-maps/dragon_war/master/description/DragonWar_mini.png
  img: https://raw.githubusercontent.com/triplea-maps/star_trek_dilithium_war/master/description/StarTrek_mini.png
  img: https://raw.githubusercontent.com/triplea-maps/star_wars_galactic_war/master/description/StarWarsGalacticWar_mini.png
  img: https://raw.githubusercontent.com/triplea-maps/star_wars_tatooine_war/master/description/StarWarsTatooineWar_mini.png
  img: https://cloud.githubusercontent.com/assets/15109713/22105137/fbb2629a-de42-11e6-901e-4d286c89bae9.png
  img: https://raw.githubusercontent.com/triplea-maps/iron_war/master/map/EXTRA/MiniSnapshot.png
  img: https://raw.githubusercontent.com/triplea-maps/map_making_tutorial/master/description/MapMakingTutorial_mini.png
```

**Comment by DanVanAtta** [comment]
>  I would rather upload it beside the README, outside of the map folder.

IIRC you can do that. As @ssoloff  mentioned, standalone files to the GitHub cloud works as well (ie: attach an image to a github issue, then just use the URL provided and cancel/close the issue comment)

> Main question is, does "fork" mean that this thing in here is stand-alone and I can go totally delete:
https://github.com/Cernelius/270bc_variants (to avoid having a duplicate around)

Yes. You should switch to using the 270bc_variants repo now hosted under triplea-maps.

**Comment by Cernelius** [comment]
Wouldn't be better to decide on an official convention, so not to have some in the cloud and some inside the repositories in different places? Guess not important.
I'd go for:
master/description/270bc_variants_mini.png
(can it be jpeg?)

**Comment by DanVanAtta** [comment]
There is no set convention on thumbnails AFAIK. larger than 400 and perhaps the UI will not look good - I do not know if that changed or not. It would be nice to spell out where thumbnails should go, and we could take advantage of that in code too.

**Comment by DanVanAtta** [comment]
@Cernelius  it does not hurt too much to experiment with jpeg, we can change it if it does not work. I don't think it *has* to be png, but I do not remember one way or another.

**Comment by Cernelius** [comment]
Ok. The thumb are a bit slow to load for me. For example, it takes 4 seconds to show the one of Civil War, after I click on it in download list, when in the Download Maps. I recall I was almost instant in the old one before 1.9. So I was suggesting to maybe use jpeg for the thumbnails.

**Comment by DanVanAtta** [comment]
File size and download speed should be the dominant factors, I would suspect those are at play over jpeg vs png, but maybe.. IMO whichever produces a smaller file size should be preferred, would be interested to know if there were a big difference just based on encoding alone.

**Comment by Cernelius** [comment]
Definitely jpeg is much smaller in file size than png, but depends on the quality (the lowest the more lossy and the smaller). The smaller lossless decently affirmed image format is WebP, but it is scarcely supported; just a side note.
Just there is not anymore the possibility of rapidly skim through the thumbs+description (as you were able to do in the old repo download), as you (or at least me) have to wait a few seconds (2-5) for each thumb to show up; that's all. Not sure if for others is much faster.

**Comment by ssoloff** [comment]
> can it be jpeg?

I just tried this...  I modified my local `triplea_maps.yaml` to reference a JPEG and it showed up just fine in the Download Maps window.

> The thumb are a bit slow to load for me.

I suspect this has more to do with the host than the image size.  A Git repo (what's backing `raw.githubusercontent.com`) is not exactly a high performance static file server. :smiley:  It might be interesting to investigate using a CDN or some other (free) image host for the thumbnails.  Maybe even `triplea-game.org`?

**Comment by Cernelius** [comment]
The one thing I immediately noticed when we moved from 1.8 to 1.9 is that in 1.8 I was able to skim through all the maps with the thumbnails showing up immediately, so that I could just glance at them and see if anything looks interesting. Now it is not anymore possible, for me, to do it, as I have to wait about 3 seconds for the image to show up after I click on that map title.

**Comment by Cernelius** [comment]
At the end I've gone with standard png and I've put the image just in main folder.

Ok I've made the pull request:
https://github.com/triplea-game/triplea/pull/1793/commits

Since "270BC Cernel Variant" is basically just "270BC" with some tweaks, limited almost only to the things that make me unconfortable the most with (I would have just updated 270BC and call it version 2.0, if I would have been the owner of it), I've decided to put it right below the original.
Let me know if you disagree with this (especially since this is High Quality), and I'll move it wherever.

**Comment by Cernelius** [comment]
Ok, all at this issue has been done.
Thanks.

It may be good if a decision is taken (or an issue is opened) about where to store the "mini" images, how to call them, and if anything can be done, and it is worth to do it, to have them showing faster, to allow new user to skim rapidly through the many maps, in search of something that might interest them (3 to 5 seconds on my end, to see the image in description, after selecting the map; I recall it was much faster, for me, to see them in 1.8.0.9).

For 270bc_variants I've done thus:

- Uploaded the thumbnail in main folder (beside the README)
- Called it as `<repository name>`_mini.png

**Comment by DanVanAtta** [comment]
FWIW, this issue: https://github.com/triplea-maps/Project/issues/16 is a bit stuck on where/what standard info to place per map. Thumbnail standard location is still being actively discussed.

**Comment by FrostionAAA** [comment]
Someone  said "I would rather upload it beside the README, outside of the map folder."

If it is OK with devs, I will move all my seven map thumbnails to a location "beside the readme file" next time I update the Yaml because of an Iron War update. I think it would be a good thing that everyone who might take over map "ownership" if a maker goes AWOL knows exactly where to find the image.

**Comment by ssoloff** [comment]
@FrostionAAA If you go through with this, maybe also consider standardizing the base name of the image (e.g. `map_thumbnail.png`).  Since each map is isolated within its own repo, it seems unnecessary to have a custom image name per map.
