### ISSUE TITLE
.gitignore, .travis.yml and build.gradle?

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-maps/Project#82]
Is it OK to delete the files .gitignore, .travis.yml and build.gradle from a map directory? Are these files used for anything now? I am just asking as I got them in all my maps, but not Iron War, and I have heard no complaining about that.

**Comment by DanVanAtta** [comment]
.travis.yml and build.gradle can certainly be deleted. 
.gitignore is a typical file in any git repository, modify to your liking, but it can also be removed too.

**Comment by FrostionAAA** [comment]
Nice. Thank You! 👍

**Comment by ssoloff** [comment]
@FrostionAAA @DanVanAtta @ron-murhammer Note that several Travis `triplea-maps` builds are now failing.  We probably need to disable Travis builds for all maps based on the discussion in this issue.

Failing builds:

https://travis-ci.org/triplea-maps/star_wars_tatooine_war
https://travis-ci.org/triplea-maps/star_wars_galactic_war
https://travis-ci.org/triplea-maps/star_trek_dilithium_war
https://travis-ci.org/triplea-maps/dragon_war
https://travis-ci.org/triplea-maps/caribbean_trade_war
https://travis-ci.org/triplea-maps/age_of_tribes

**Comment by DanVanAtta** [comment]
Perhaps failing because I deleted the access tokens in the bot. Seems like we need to clone all the map repos and then run a travis (their ruby app) disable on each.

**Comment by ssoloff** [comment]
@DanVanAtta I think it's simply because `.travis.yml` was deleted and Travis is falling back to a "default" build script.  From one of the logs:

```
Could not find .travis.yml, using standard configuration.
```

And then the final build error is

```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Instead of cloning all the repos, it might be easier to just use the profile page for the `triplea-maps` org in the web interface and flip the toggle on every repo since they're all on one page:

![travis](https://user-images.githubusercontent.com/4826349/26933781-87978672-4c35-11e7-954a-940ebe7f5001.png)

**Comment by DanVanAtta** [comment]
Good suggestion, now done - 291 travis map builds turned off.
![291_repo](https://user-images.githubusercontent.com/12397753/26944707-565d9bd8-4c3e-11e7-99cf-a5bea08efecb.png)
