### ISSUE TITLE
Adding WW2v3-1941-MBM WW2v3-1942-MBM WW2v3-1941-TechAdvance Inside ww2v3_variants And Updated Objectives Properties

### ISSUE THREAD

**Issue by Cernelius** [triplea-maps/Project#83]
Just pushed the addition of 3 new mods in ww2v3_variants games:
WW2v3-1941-MBM
WW2v3-1942-MBM
WW2v3-1941-TechAdvance
And updated the objectives.properties, for them.

https://github.com/triplea-maps/ww2v3_variants/pull/3

**Comment by Cernelius** [comment]
This is the pull request for updating descriptions in download list.

https://github.com/triplea-game/triplea/pull/2060

**Comment by Cernelius** [comment]
I forgot to update the version, in my previous pull request. This does it:

https://github.com/triplea-game/triplea/pull/2061

**Comment by ssoloff** [comment]
@Cernelius Your new mods should be available.  Can you please verify and close this issue if everything checks out?

**Comment by Cernelius** [comment]
And I added 1 end line too much... This removes it:

https://github.com/triplea-game/triplea/pull/2062

So, yes, hopefully that is the last thing. I verify now.

**Comment by Cernelius** [comment]
Seems all good. Thanks.
