### ISSUE TITLE
Updating WW2v3-1941-TechAdvance Inside ww2v3_variants To Version 1.8

### ISSUE THREAD

**Issue by Cernelius** [triplea-maps/Project#84]
I want to upgrade the game "WWIIv3 1941 Tech Advance" to version 1.8.
Please, merge this commit:
https://github.com/triplea-maps/ww2v3_variants/pull/4
And merge this commit:
https://github.com/triplea-game/triplea/pull/2095

Main changes:
- Corrected battleship to have 2 hitpoints.
- Made "Cat 4" default option.
- Updated game notes.

**Comment by DanVanAtta** [comment]
thank you. Reviewed both and saw no problem, both are now merged
