### ISSUE TITLE
Napoleonic Empires Changes Proposal 2017/07/28

### ISSUE THREAD

**Issue by Cernelius** [triplea-maps/Project#87]
I suggest **switching the "Hussars" and "Dragoons" images**, while **renaming the "Hussars" to "Light_Horses".**
This would have the "Dragoons" having a good image for it, while the "Hussars" would be called "Light_Horses" and have the image of a Polish Light-Horse Lancer.
I request acceptance of this suggestion by the general admins and, if so, I would push the changes myself for napoleonic_empires and its mapskin (I'm not asking for any ownerships; so you would have to accept it again after the push is made).

The above is my main problem, and I would be content if that only is accepted, but, besides this, I also suggest:
**Howitzer->Howitzers**
**Artillery->Cannons**

If everything is accepted, I would, then, proceed with the push.

More in detail:

I think the main visual problem of this map is that you have to see a "Hussars" unit that, unless I'm missing something, it is not a hussar, or anything the like, but it rather seems to be representing a "Dragoon", which in turn is represented by what it is clearly a Polish lancer, that it is a light-horse unit, like the hussars (tho I guess the fact that a bunch of French dragoons regiments were converted to lancers in a way tempers the nonsense of seeing a lancer called dragoon). 

Without making new images, I suggest: 
- In the skin, renaming the "Hussars" to "Dragoons" and the "Dragoons" to both "Hussars" and "Light_Horses". 
- In the xml, renaming "Hussars" to "Light_Horses". 

This would: 
- Use the current "Hussars" image for the "Dragoons", which seems good, as that could really be representing a dragoon (but surely not any kind of light cavalry). 
- Use the current "Dragoons" image for the "Hussars", but rename it to "Light_Horses", as it would look strange to see a lancer depicting a hussar (tho they are both light cavalry). 
- Having a "Hussars" image still in the folder, for full backward compatibility.

Discussion open in:
http://tripleadev.1671093.n2.nabble.com/Empires-Napoleonic-Wars-tp4696030p7595740.html

I think all these changes are fairly obvious and would have no compatibility problems, so I hope they can be considered and accepted soon (I don't think we will get much discussion in forum).

**Comment by Cernelius** [comment]
To be clear, the backward compatibility would be assured by leaving all the images with the previous names in the folders, albeit the "Hussars" would be switched to the "Dragoons" image too.
As far as the xml is concerned, the changes would be only:
Hussars->Light_Horses
Howitzer->Howitzers
Artillery->Cannons

**Comment by Cernelius** [comment]
Additionally, while being at it, I also suggest changing:
**Brigantine->Brig**
(keeping Brigantine in the folder)

That is very clearly a brig (more properly, a gun-brig), or at least a brig-rigged vessel, like a brig-sloop, and surely not a brigantine, but I'm not too much bothered by this, but I'd change it as well, if you are fine with it.
The other ships names are fairly acceptable, tho the Barque appears of antiquate concept (talking about the riggings, of course).

And, just thought about it, I will also change the names that you see on the board display (right part of the map), for completess.

**Comment by Cernelius** [comment]
So, basically, I know I could just do it and ask you to accept the push, but, since it would a bit of work, I would like to have the general admin acceptance before doing that (you can still, then, refuse if you think I didn't do it right, of course).

Thank you.

**Comment by Cernelius** [comment]
Hoping to get an answer soon. Would be great if this can be pushed, accepted and closed in a couple days.

**Comment by Cernelius** [comment]
Ah. And I would switch over the "I" and "II" signs in the images, but leaving the originals in the folders.

Practically, the matter is like if you would see a unit called ArmouredCar that has the image of an armour; that is about the same thing as seeing a horseman with a straight sabre and a helmet called Hussars; plus seeing a Polish lancer called Dragoons is not great, either.

Another reason for changing Brigantine to Brig, beside the fact that the unit is depicting a brig-rigged vessel, not a brigantine-rigged one, is that brigs were much more related to the scenario than the, by then, very marginal brigantines; of course, that unit would represent not only straight gun-brigs, but other stuff too, most likely comprising the very few brigantines, but definitely having a unit called Brig would feel itself much better than having a unit called Brigantine, that is almost totally out of place for 1800 Western Europe.

The other item is that a Corvette, for the time, is a French only concept, while a Cutter is mainly an English one, but, since there are Chasseurs etc., I think Corvette is coherent, and I don't see clearly better alternatives to Cutter, but anyways I think this is somewhat acceptable and they both can stay as they are called.

The Howitzer to Howitzers is because all other mobile land units are plural and the Artillery to Cannons is because at least Howitzer(s) and Mortars are artillery too, so that is not making sense.

**Comment by FrostionAAA** [comment]
I think the name changes would make the map a bit more true to history and uniforms. I like:
Howitzer->Howitzers
Artillery->Cannons
Brigantine->Brig
Hussars->Dragoons
Dragoons->? (I would say Lancer) 
I would advocate for not using a general term like Light Horses. I think the original intention was to have this map use very well known cavalry types like Hussars and Dragons, not light and/or heavy cavalry or horses. Clearly the art has it all wrong at the moment, and the current Dragoon is most likely an Uhlan. But would it then not be more appropriate to name this unit "Lancer"? This would, like the other cavalry names be a specific historical and well known unit type. Technically the Uhlans were also "Lancers" and all nations could have Lancer cavalry in one shape or another.

**Comment by Cernelius** [comment]
> I would advocate for not using a general term like Light Horses. I think the original intention was to have this map use very well known cavalry types like Hussars and Dragoons, not light and/or heavy cavalry or horses.

Indeed, except only that Light Horses is not a general term; Light Cavalry would be.

So, I want to precise that I believe the best solution would be making a new unit image of an actual hussar, and call it "Hussars", while renaming the current "Hussars" image to "Dragoons". However these proposals were meant to be limited by not making new images.

Actually, "Light_Horses" is only apparently a general term, but actually a very specific and niche one, for the French. It is not saying Light Cavalry (which would be general), but it is the Anglicization of "Chevaulegers", since the map uses a French naming perspective worded in English (otherwise you would not have Chasseurs, Cuirassiers, Corvette etc. units).
The actual name of the French lancers was "chevau-légers lanciers", so either "Light_Horses" (from "Chevau-Legers") or "Lancers" (from "Lanciers") or the full "Light_Horses_Lancers" would specifically mention them alike.
I would exclude "Light_Horses_Lancers" for being too long and I think that both "Light_Horses" and "Lancers" are good, and probably "Lancers" would sound better to the average player and be more user friendly for noobs, on the account of the unit clearly holding a lance.
My preference of "Light_Horses" over "Lancers" (both from "chevau-légers lanciers") stems from several reasons:
- In the French army, this unit would factually represent the sum of Horse-Chasseurs, Hussars and Light-Horses Lancers, plus other minor specialties, like the Mamluks, the Eclaireurs and the Krakusi, with the Horse-Chasseurs being by far the numerically prevalent one, followed by the Hussars. Hence, while "Light_Horses" is not actually a general term, I intended the general sound of it to be preferable over the more specifically sounding "Lancers", for something that would represent a bunch of cavalries of which the lancers would actually be only a very small fraction.
- In my mind, while during Napoleonic times the lancers were indeed all light cavalry on small horses, the term "Lancers" doesn't communicate the idea of something being necessarily light, but rather just the way the horseman is armed.
- Even for the "chevau-légers lanciers" themselves, only about half of them were actually armed with lances, thus the term "Light_Horses" seems the more comprehensive of the two parts.
- The lancers in the French army existed only starting from 1809, yet very sparingly, and only from 1811 as a series of standard regiments. So, since the "Lancers" are for the French something that exists at all only very late in the scenario, I prefer the more generic sounding "Light_Horses", that can be read better in the moment in which you are looking at a 1794 scenario, in which nobody at all in the French army used lances (as well as nobody at all in all of western Europe and only the Poles in all of central Europe), but there were light cavalry units called Horse-Chasseurs and Hussars only, for which the term "Light_Horses" would be descriptively fitting, but definitely not the term "Lancers". Again, on this point, it would be much better having an actual hussar unit and call it "Hussars".
https://www.napoleon-series.org/military/organization/c_lancers.html

With this said, I'm fine both with "**Light_Horses**" and with "**Lancers**" (still suggest "Light_Horses") and, one way or the other, I would add both as images in the folder.
So if an admin can just decide and pick one of the two, and otherwise agree with this proposal, then I would soon go ahead with the push.
Thanks.

**Comment by FrostionAAA** [comment]
I dont think that just because french would use "Light Horse" as general term for a portion of their cavalry units, including some lancer units, that this would make it a good term for every nations' lance equipped cavalry. The unit picture of the lance cavalry, could be a French Chevau-Légers (Light Horse), probably then a Dutch or Polish Lancer unit in French service. But even French would say Chevau-Légers Lanciers, if they wanted to be more specific about the arms and capabilities of this unit. So in my mind even French would be fine with the term Lancer. And no one would be in doubt about the gear and characteristic of a Lancer, noob or expert.

**Comment by Cernelius** [comment]
> I dont think that just because french would use "Light Horse" as general term for a portion of their cavalry units, including some lancer units, that this would make it a good term for every nations' lance equipped cavalry.

No: I believe the French actually termed "chevau-légers" (light-horses) all of the lancers and nothing else but the lancers (in Austria, instead, "chevauxleger" was the name for sabre cavalry like the French horse-chasseurs or the English light dragoons).
Anyways, as I said, that unit would not possibly be representing the very rare and very late (and totally inexistent for many countries, like the United Kingdom) partially lance equipped cavalry (for example, the English never had any, and the French themselves had any only over 10 years after the Egypt expedition, to give a timeline). Just as the unit named "Hussars" is doing now, the newly named unit using the current "Dragoons" image would most likely represent any kind of light cavalry, comprising the  lancers, and, for any scenario before 1809 that unit would not represent any lancers at all for the French either, but just only or mostly Horse-Chasseurs and Hussars. For the English, that unit, call it "Light-Horses" or "Lancers", would be representing mostly the "light dragoons"; for the Austrians, it would be representing mostly the "hussars" and the "chevauxlegers"; for the Prussians, it would be representing mostly the "hussars"; for the Russians, it would be representing mostly the "cossacks" (that were actually armed mainly with lances).
Anyways, that image currently assigned to the Dragoons is surely a Polish Light Horse Lancer of the French Army and I think it is ok to call it either "**Light_Horses**" or "**Light-Horses**" or "**Lancers**", and I'm ok with any of them.
So if an admin can give an answer on this issue and pick one name that would be great, so I can push all of the above changes, if no other doubts. I hope this can be done soon, as all the changes, except "light-horses" vs "lancers" (I'm ok with either), are pretty obvious, but I need the approval of an admin. Thanks.

**Comment by Cernelius** [comment]
> the French actually termed "chevau-légers" (light-horses) all of the lancers and nothing else but the lancers

Actually, to be correct, those "chevau-légers lanciers" originating from the cavalry of the Vistula Legion were previously named "Vistula Lanciers" and the "chevau-légers lanciers" of the Imperial Guard were called only "chevaux-légers" before being rearmed with lances, but these are all intermediate phases. Ultimately, there were only "chevau-légers lanciers" and no unit was termed chevau-légers but not lanciers or lanciers but not chevau-légers, tho there was another case of a, differently named, French unit armed with lances, namely the "eclaireurs" (very late units operative since 1814).

**Comment by Cernelius** [comment]
Another straight argument in favour of switching the Dragoons and Hussars images is that the level I cavalry has now a clearly bigger horse than the level II cavalry; so the dude armed with the lance (currently called Dragoons, and to be renamed as Light-Horses or Lancers) would fit best as level I cavalry, for having the smaller horse.
So, just waiting for the input from an admin, since I'm not the owner of napoleonic_empires and don't want to do all the stuff if there might be no interest about these changes at all.
As I said, I believe the most important change is switching the Dragoons and Hussars images; so that is a must for me, while the rest are additions. I'm also fine with keeping the same names, while switching, tho seeing a lancer called Hussars would not be that much better than seeing a lancer called Dragoons.
Having to see that Dragoon-like cavalry called Hussars is really bad and the biggest issue for me.

**Comment by FrostionAAA** [comment]
As this is a game, I would say that the exact date of when each country introduced or (re)introduced lancer regiments during the war is not that important. If we say that the Napoleonic wars ended in 1815, the only country that might be problematic is Great Britain, as they apparently first introduced lancer regiments in 1816 (http://theroyallancers.org/regimental-history/). 

As Lancers got a revival under the Napoleonic times, and are maybe best know for their roles in these wars, I still can’t see a problem with them being represented, both graphically or by name. For historical accuracy, the map’s starting units could just be set to only have some countries start out with Lancers, thereby let the players determine when their respective countries should introduce Lancers during the war :-)

I would also say that the very best solution to the naming problem and problematic unit picture would be to have a totally new hussar unit picture, and then have the unit be called hussar. Do we know of any graphical artist that can make a new unit picture in the same style as the old ones? Who made the old unit pictures?

PS: I think the most neardy Napoleonic history page I know of, that describes units and war tactics is maybe http://napoleonistyka.atspace.com/

**Comment by Cernelius** [comment]
> For historical accuracy, the map’s starting units could just be set to only have some countries start out with Lancers, thereby let the players determine when their respective countries should introduce Lancers during the war :-)

These proposals are not gameplay related and, as such, "Light-Horses" or "Lancers" would be exactly were "Hussars" currently are and, as I said, I'm fine with either names, so, since I don't believe anyone can have a problem with any other of the proposals, now we are just waiting for an admin to pick and consent...

**Comment by Cernelius** [comment]
To summarise clearly, now I'm just **waiting that an admin agrees with the changes and decides how to rename the Dragoons** (either Light-Horses or Lancers):

Game changes:

Hussars->Light-Horses/Lancers
Howitzer->Howitzers
Artillery->Cannons
Brigantine->Brig

Graphic changes:

Hussars->Dragoons
Dragoons->Light-Horses/Lancers
Howitzer->Howitzers
Artillery->Cannons
Brigantine->Brig

Change "I" to "II" in the current Hussars image.
Change "II" to "I" in the current Dragoons image.
Update the unit list image in the board.

All would be done assuring backward compatibility.

**Comment by Cernelius** [comment]
Anyone? It would be also an option to switch Dragoons-Hussars leaving the same names. At least this way the Dragoon will be fine, while the Hussars will pass from having a Dragoon image to having a Lancer image, which is not really worse, plus the smaller horse would be assigned to the weaker unit.

**Comment by ssoloff** [comment]
> I'm just waiting that an admin agrees with the changes

@Cernelius In map repos, I was previously told to explicitly tag @ron-murhammer and @DanVanAtta when I wanted their attention.  I don't think they receive notifications for these issues otherwise.

**Comment by DanVanAtta** [comment]
FWIW I get notifications. @ron-murhammer may be a better admin for Nap Wars, I've almost no experience on the map. Changes mentioned do sound reasonable to me.

**Comment by Cernelius** [comment]
Ok; just waiting. Plus this is just asking if there is any point, as the true decision would be on what I push. Please don't miss the Light-Horse vs Lancers discussions. I prefer Light-Horses and @FrostionAAA prefers Lancers, but I believe both are better then current, and I'll go with either, or even just leaving Hussars and switching the images.
To give some more context, I'm making another map using this skin, and I'm going to switch Hussars and Dragoons in there; so I would prefer things being similar, or it would be confusing if light vs medium cavalry are the opposite images here and there. Of course, this doesn't matter for this one, as the changes should be valued only if better for this map itself.
I realise that many suggestions are not as obvious as if you would see a LightArmour with the image of a Tiger Tank in WW2.

**Comment by ron-murhammer** [comment]
@Cernelius The changes sound good to me. I don't have a strong opinion on Light-Horse vs Lancer.

A side note is I think unit name should be singular not plural as I think the engine looks to add 's' to the end when you have multiple of the same units.

**Comment by Cernelius** [comment]
Thanks for the answer.

I definitely believe that maps should not be forbidden using plural names based on the limits of the engine.
Also considering that "Artillery" becomes "Artillerys", "Horse_Artillery" becomes "Horse_Artillerys" and "Fortress" becomes "Fortresss" (yes, with three "s"), all singular names, I would not change all names to singular just to try to follow the very incomplete pluralisation system of the engine, anyways.
I'm not actually even sure how that is meant to work, actually, since I see that "artillery" becomes "artilleries", but "Artillery" becomes "Artillerys", while, instead, "infantry" remains "infantry".
I guess I can open an issue about this. I never did because the matter is so marginal I have never been really bothered.
But, yes, I agree that seeing two or three "s" end name is not polished, and the engine should avoid adding "s" to plural names, as well adding "es", instead of "s", to singular names ending in "s".

Personally, my preference is using plural names for everything that can't be representing a single "real" unit (and this is what I'm having in a map of mine I'm making) and, yes, it would be good if the engine would not, then, add an "s" after it.
So, here, I would have all names plural except "Fortress" singular, but that's just my preference, and I'm not pushing it.
Definitely I prefer "Fusiliers" etc. over "Fusilier" as, in my mind, that is "a unit of Fusiliers", but "Fusilier" is ok too, as you would be referring to the piece of the boardgame you are moving around, not to what it is meant to represent.
This is just a matter of personal preference, depending if one think that the name should name the piece or should name the unit that piece is representing.

Aside from the Marshals, what the game actually does, already, with the only exception of "Howitzer" (Artillery and Horse_Artillery are not actual exceptions, as they are conceptually not necessarily referring to 1 single piece), is having all land mobile units plural and all immobile land units, factories and ships singular.
This should be the intended convention, also considering that the "Howitzer" was an addition, not part of the original map and not one of the images made by the original creator.
I think we can keep this convention, thus why the only change related to this matter is "Howitzer" to "Howitzers", for consistency.

In general, I've kept the changes limited to stuff that it is clearly wrong to start with, not just changing what I prefer. For example, I prefer "Redoubt", or rather "Redoubts", over "Mortella_Tower", but I'm leaving that alone.
I'm actually thinking to change "Mortella_Tower" to "Mortella_Towers", if that is fine, while leaving "Fortress" singular as is, since the "Fortress" might represent a single one, while the "Mortella_Tower" is definitely representing multiple.

**Comment by Cernelius** [comment]
Ah, I've seen in the changelog that you have written:

> Renamed from Napoleonic Empire to Napoleonic Empires.

But, actually, the game was already called "Napoleonic Empires". What you changed is the map folder name, from "napoleonic_empire" to "napoleonic_empires" (and, of course, the "mapName", but not the "info name").

Can I just delete that line from the changelogs? I'm guessing you got confused, and thought to have changed both? The problem was that the games were "Empires", while the map name was "empire", so I don't believe any games' names were changed.

**Comment by ron-murhammer** [comment]
@Cernelius Yeah you can remove it from the changelog.

**Comment by Cernelius** [comment]
I'm going to have in the folder the same image called "**Light-Horses**", "**Lancers**", "**Light_Lancers**", "**Light-Horses_Lancers**" and "**Uhlans**", and use "Light-Horses" in the xml.
Having all the versions means full backwards and forward compatibility, from this point on, thus anyone can switch anytime, with no problems, and also make a mod with the preferred name, playing it with anyone.

**Comment by Cernelius** [comment]
I'm probably doing a small rerun of the placement picker, to get a few placements more here and there, while I'm at it.

**Comment by DanVanAtta** [comment]
@Cernelius closing for now, please re-open if this is still an active topic.
