### ISSUE TITLE
Correcting WW2v3-1941-MBM, WW2v3-1942-MBM Inside ww2v3_variants (2017/08/31)

### ISSUE THREAD

**Issue by Cernelius** [triplea-maps/Project#88]
I removed wrong "end comment" signs in both:
WW2v3-1941-MBM.xml
WW2v3-1942-MBM.xml

Please, merge:
https://github.com/triplea-maps/ww2v3_variants/pull/5
https://github.com/triplea-maps/ww2v3_variants/pull/6

**Comment by Cernelius** [comment]
I don't intend to change or update the download description or version number.

**Comment by ssoloff** [comment]
Thanks, @Cernelius.  Both PRs have been merged.

**Comment by ssoloff** [comment]
@Cernelius I don't have permission to close issues in this repo, so if you would be so kind... :smile:
