### ISSUE TITLE
Map Categories

### ISSUE THREAD

**Issue by williamdekryger** [triplea-maps/Project#9]
I'm creating this issue so we can discuss the classification of maps into a number of different categories. This has been discussed by me and @DanVanAtta as of yet, especially for inclusion into the website, but let's lay out:

- Which categories we want
- How we want them to display (on the website, in the game, etc.)
- Who we would like to do the classification (the map-maker or the mod)
- Anything else related to this topic

**Comment by DanVanAtta** [comment]
I'm a bit concerned categories may not have future proofing, so we should be a bit careful about what we pick in case someone creates a map that does not fit well into any of our categories. How do you envision categories working, where do you see them being used?

**Comment by williamdekryger** [comment]
Well, it all depends on the limitations that Jekyll gives us. They have a taxonomy system, be it simple. Each map would just put what category it is in in the [YAML Front Matter] (http://jekyllrb.com/docs/frontmatter/). Then we would have a listing page for each category (hopefully). Perhaps the in-game map downloader could someday be able to parse the categories and allow users to filter maps by categories. More coming on the YAML Front Matter. Categories we would make would not necessarily be only time periods, as we do have several anachronistic maps. I agree on future-proofing, though Markdown is here to stay, as far as I can tell, especially with the bonus that it looks decent even when not rendered, though we could do it in JSON...

**Comment by DanVanAtta** [comment]
Perhaps what it gets down to, having a standard file in each map repository that we can parse. YAML would be my vote for syntax. The file could a link to a thumbnail image, larger image, references to other files even as well (quite flexible). One such item in the YAML could be the "mapCategory". @williamdekryger ,what do you think?

**Comment by DanVanAtta** [comment]
Of note here, chances are good maps objects in the game will be given  'metadata' fields, such as "time period", "suggested number of players", "popularity", which will allow people to sort and filter on them.
